server:
  port: 8011
  servlet:
    session:
      timeout: 10m
spring:
  datasource:
    username: wtdbuser
    password: wtdbuser
    url: jdbc:mysql://bj-cdb-hgkqwllz.sql.tencentcdb.com:63308/wt-db?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.jdbc.Driver
  mvc:
    view:
      prefix: calsspath:/templates/
      suffix: .html

mybatis:
  mapper-locations: classpath:/mappers/*.xml
  type-aliases-package: com.example.analysis.bean
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#pagehelper:
#  helper-dialect: mysql
#  reasonable: true
#  support-methods-arguments: true
#  params: count=countSql